site_name: perms.io docs
site_url: https://docs.perms.io/
theme:
  name: material
  logo: assets/favicon.png
  favicon: assets/favicon.png
  palette:
    scheme: slate
    color: custom
  nav:
    Getting Started: getting-started.md
    IAM Basics: getting-started.md
extra_css:
  - stylesheets/extra.css