site_name: Documentation
site_url: https://docs.perms.io/
theme:
  name: material
  logo: assets/transparentLogo.png
  favicon: assets/favicon.png
  palette:
    scheme: slate
    color: custom
extra_css:
  - stylesheets/extra.css